export { default as BaseLayout } from './BaseLayout.vue'
export { default as BaseTabs } from './BaseTabs.vue'
export { default as BaseInput } from './BaseInput.vue'
export { default as BaseButton } from './BaseButton.vue'
export { default as BaseHeading } from './BaseHeading.vue'
export { default as BaseModal } from './BaseModal.vue'
export { default as BaseHeader } from './BaseHeader.vue'
